# Generated by Django 4.2.3 on 2023-07-10 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'ADMIN'), ('SPECIALISTE', 'SPECIALISTE'), ('ENCADREUR', 'ENCADREUR')], default=1, max_length=50, verbose_name='Rôle'),
            preserve_default=False,
        ),
    ]
