# Generated by Django 4.2.3 on 2023-07-10 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_role'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Module',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='module',
            new_name='categories',
        ),
    ]
